<a href="https://colab.research.google.com/github/mundevaishnavi13/Artificial_Intelligence_Lab_SE_A_42/blob/master/dse5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [13]:
from google.colab import drive
uploaded=files.upload()

Saving student dataset.csv.zip to student dataset.csv (1).zip

In [ ]:
import pandas as pd

df = pd.read_csv('student_math_clean.csv')
display(df.head())

,student_id,school,sex,age,address_type,family_size,parent_status,mother_education,father_education,mother_job,...,family_relationship,free_time,social,weekday_alcohol,weekend_alcohol,health,absences,grade_1,grade_2,final_grade
0,1,GP,F,18,Urban,Greater than 3,Apart,higher education,higher education,at_home,...,4,3,4,1,1,3,6,5,6,6
1,2,GP,F,17,Urban,Greater than 3,Living together,primary education (4th grade),primary education (4th grade),at_home,...,5,3,3,1,1,3,4,5,5,6
2,3,GP,F,15,Urban,Less than or equal to 3,Living together,primary education (4th grade),primary education (4th grade),at_home,...,4,3,2,2,3,3,10,7,8,10
3,4,GP,F,15,Urban,Greater than 3,Living together,higher education,5th to 9th grade,health,...,3,2,2,1,1,5,2,15,14,15
4,5,GP,F,16,Urban,Greater than 3,Living together,secondary education,secondary education,other,...,4,3,2,1,2,5,4,6,10,10

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             395 non-null    int64
 1   school                 395 non-null    object
 2   sex                    395 non-null    object
 3   age                    395 non-null    int64
 4   address_type           395 non-null    object
 5   family_size            395 non-null    object
 6   parent_status          395 non-null    object
 7   mother_education       395 non-null    object
 8   father_education       395 non-null    object
 9   mother_job             395 non-null    object
 10  father_job             395 non-null    object
 11  school_choice_reason   395 non-null    object
 12  guardian               395 non-null    object
 13  travel_time            395 non-null    object
 14  study_time             395 non-null    object
 15  class_failures         395 non-null    int64
 16  school_support         395 non-null    object
 17  family_support         395 non-null    object
 18  extra_paid_classes     395 non-null    object
 19  activities             395 non-null    object
 20  nursery_school         395 non-null    object
 21  higher_ed              395 non-null    object
 22  internet_access        395 non-null    object
 23  romantic_relationship  395 non-null    object
 24  family_relationship    395 non-null    int64
 25  free_time              395 non-null    int64
 26  social                 395 non-null    int64
 27  weekday_alcohol        395 non-null    int64
 28  weekend_alcohol        395 non-null    int64
 29  health                 395 non-null    int64
 30  absences               395 non-null    int64
 31  grade_1                395 non-null    int64
 32  grade_2                395 non-null    int64
 33  final_grade            395 non-null    int64
dtypes: int64(13), object(21)
memory usage: 105.1+ KB

In [17]:
df.describe()

,student_id,age,class_failures,family_relationship,free_time,social,weekday_alcohol,weekend_alcohol,health,absences,grade_1,grade_2,final_grade
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,198.000000,16.696203,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,114.170924,1.276043,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,1.000000,15.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,99.500000,16.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,198.000000,17.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,296.500000,18.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,395.000000,22.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [18]:
df['age'].describe()

count    395.000000
mean      16.696203
std        1.276043
min       15.000000
25%       16.000000
50%       17.000000
75%       18.000000
max       22.000000
Name: age, dtype: float64

In [33]:
import pandas as pd

# Load dataset using the correct filename
df = pd.read_csv("student_math_clean.csv")

# Display original dataset
print("Original Dataset:")
display(df.head())

# Filtering condition using correct column names and condition for study_time
filtered_data = df[(df['age'] > 18) & (df['study_time'] == '>10 hours')]

# Display filtered dataset
print("\nFiltered Dataset (Age > 18 and StudyHours > 10):")
display(filtered_data)

Original Dataset:

,student_id,school,sex,age,address_type,family_size,parent_status,mother_education,father_education,mother_job,...,family_relationship,free_time,social,weekday_alcohol,weekend_alcohol,health,absences,grade_1,grade_2,final_grade
0,1,GP,F,18,Urban,Greater than 3,Apart,higher education,higher education,at_home,...,4,3,4,1,1,3,6,5,6,6
1,2,GP,F,17,Urban,Greater than 3,Living together,primary education (4th grade),primary education (4th grade),at_home,...,5,3,3,1,1,3,4,5,5,6
2,3,GP,F,15,Urban,Less than or equal to 3,Living together,primary education (4th grade),primary education (4th grade),at_home,...,4,3,2,2,3,3,10,7,8,10
3,4,GP,F,15,Urban,Greater than 3,Living together,higher education,5th to 9th grade,health,...,3,2,2,1,1,5,2,15,14,15
4,5,GP,F,16,Urban,Greater than 3,Living together,secondary education,secondary education,other,...,4,3,2,1,2,5,4,6,10,10

Filtered Dataset (Age > 18 and StudyHours > 10):

,student_id,school,sex,age,address_type,family_size,parent_status,mother_education,father_education,mother_job,...,family_relationship,free_time,social,weekday_alcohol,weekend_alcohol,health,absences,grade_1,grade_2,final_grade
210,211,GP,F,19,Urban,Greater than 3,Living together,secondary education,secondary education,other,...,4,3,3,1,2,3,10,8,8,8

In [ ]:
import pandas as pd

# Load dataset using the correct filename
df = pd.read_csv("student_math_clean.csv")

# Display dataset
print("Student Dataset:")
display(df.head())

# Aggregation functions (only for numerical columns)
aggregation = df.agg({
    'age': ['count', 'mean', 'min', 'max', 'sum']
})

print("\nAggregation Results:")
print(aggregation)

Student Dataset:

,student_id,school,sex,age,address_type,family_size,parent_status,mother_education,father_education,mother_job,...,family_relationship,free_time,social,weekday_alcohol,weekend_alcohol,health,absences,grade_1,grade_2,final_grade
0,1,GP,F,18,Urban,Greater than 3,Apart,higher education,higher education,at_home,...,4,3,4,1,1,3,6,5,6,6
1,2,GP,F,17,Urban,Greater than 3,Living together,primary education (4th grade),primary education (4th grade),at_home,...,5,3,3,1,1,3,4,5,5,6
2,3,GP,F,15,Urban,Less than or equal to 3,Living together,primary education (4th grade),primary education (4th grade),at_home,...,4,3,2,2,3,3,10,7,8,10
3,4,GP,F,15,Urban,Greater than 3,Living together,higher education,5th to 9th grade,health,...,3,2,2,1,1,5,2,15,14,15
4,5,GP,F,16,Urban,Greater than 3,Living together,secondary education,secondary education,other,...,4,3,2,1,2,5,4,6,10,10

Aggregation Results:
               age
count   395.000000
mean     16.696203
min      15.000000
max      22.000000
sum    6595.000000